#!/bin/bash

NO_ARGS=0;

if [ $# -eq "$NO_ARGS" ] ;  # Script invoked with no command-line arguments
then
  echo "Usage: ./`basename $0` run_number "
  exit 1          # Exit and explain usage, if no argument(s) given.
fi  

runNum=$1;

if [ $runNum -gt 999 ] || [ $runNum -lt 100 ] 
then
    echo "Out of supported runNum range"
    exit 3;
fi

##make sure that the input root files are present

fileName=run-0${runNum}

numFiles=-1;

if [ -f "${fileName}-00.root" ];
then

    numFiles=`ls ${fileName}*.root | awk '{if($0 !~/output/){print}}' | wc -l`;
    echo "Found $numFiles files for $fileName"
fi


if [ $numFiles -eq -1 ]; then
    echo "Something went wrong"
    echo "Could not find the input files"
    exit 1;
fi
num=0;
for ((sigma=9;sigma<15;sigma++)); do
    num=$(($num + 1));
    ##Bash doesn't like decimals so sigma is divided by 10 within builder
    ./EvtBuilder $runNum numFiles:${numFiles} timingMode:fitting sigma:${sigma} &> log_${sigma} &
    
done

echo Started $num processes
