#!/bin/bash

NO_ARGS=0;

if [ $# -eq "$NO_ARGS" ] ;  # Script invoked with no command-line arguments
then
  echo "Usage: ./`basename $0` runNumber Name_Of_input_File "
  exit 1          # Exit and explain usage, if no argument(s) given.
fi  

runNum=$1
fileName=$2

if [ ! -f ${fileName} ];
then
    echo "Cant Find " ${fileName} "exiting..."
    exit
fi

FileNameFull=$(pwd)/${fileName}

if [ ! -f ${FileNameFull} ]; then
    echo "Can't find " ${FileNameFull} "exiting..."
    exit;
fi

echo "FILE FULL IS " $FileNameFull

FullCommand=$(pwd)/"GammaBuilder"
echo $FullCommand
if [ ! -f ${FullCommand} ]; then
    echo "Can't find " ${FullCommand} "exiting..."
    exit;
fi




num=0;

for ((LG=12;LG<18;LG++));do
    for ((SG=4;SG<8;SG++));do
	num=$(($num + 1));
##	SubmitSeaside.sh ${FullCommand} $runNum inputFile:${FileNameFull} LG:${LG} SG:${SG} &
	SubmitSeaside.sh ${FullCommand} $runNum  LG:${LG} SG:${SG} &
    done	    
done


