#!/bin/bash

NO_ARGS=0;

if [ $# -eq "$NO_ARGS" ] ;  # Script invoked with no command-line arguments
then
  echo "Usage: ./`basename $0` run_number "
  exit 1          # Exit and explain usage, if no argument(s) given.
fi  

runNum=$1;


if [ $runNum -gt 999 ] || [ $runNum -lt 100 ] 
then
    echo "Out of supported runNum range"
    exit 3;
fi

##make sure that the input root files are present

fileName=run-0${runNum}

numFiles=-1;

if [ -f "${fileName}-softwareCFD-output.root" ];
then

  numFiles=1	   
  echo "Found $numFiles files for $fileName"
fi


if [ $numFiles -eq -1 ]; then
    echo "Something went wrong"
    echo "Could not find the input files"
    exit 1;
fi
num=0;

name=${fileName}-softwareCFD-output.root

for ((i=10;i<12;i++)); do
    for ((j=22;j<25;j++)); do
./NeutronCorrection $runNum inputFile:$name LG:$j SG:$i &> log_SG${i}_LG${j} &

done 

done

